# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

Vectors are strictly 1 dimensional array.Matrices are 2 dimensional array.

**2. How to import `NumPy` library?** 

In [1]:
import numpy

**3. Convert the given Python list into NumPy array and check its data type**

In [3]:
list_1 = [1,2,3,4,5]

In [4]:
Array=numpy.array(list_1)
Array

array([1, 2, 3, 4, 5])

In [5]:
Array.dtype

dtype('int32')

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [6]:
numpy.arange(6)

array([0, 1, 2, 3, 4, 5])

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [7]:
numpy.zeros(5)

array([0., 0., 0., 0., 0.])

array([ 0.,  0.,  0.,  0.,  0.])

**6. Generate the following `matrix`.**

In [8]:
numpy.zeros(12).reshape(3,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [10]:
numpy.ones(5) 

array([1., 1., 1., 1., 1.])

[ 1.  1.  1.  1.  1.]


**8. Generate an array of "5" tens.**

In [11]:
10*numpy.ones(5) 

array([10., 10., 10., 10., 10.])

array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [12]:
num=numpy.arange(50,100,2)
num[1:]

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [13]:
numpy.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [14]:
num1=numpy.arange(25)
num1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
# Generating vector array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [15]:
numpy.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
num1.shape=(5,5)
num1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [17]:
numpy.arange(0.1,2.6,0.1).reshape(5,5)

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [18]:
num1=numpy.linspace(0,24,25,dtype=int).reshape(5,5)
num1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
print(num1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**14. What is the main difference between `linspace()` and `arange()`?**

In [24]:
# Please consult the lectures. 
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.
linSpace=numpy.linspace(1,100,100)
linSpace

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [26]:
Arange=numpy.arange(1,100,100)
Arange

array([1])

**15. How to generate a single random integer number using NumPy built-in function?**

In [21]:
numpy.random.randint(1,5) 

4

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [20]:
numpy.random.rand(7,5)

array([[0.49913426, 0.35460871, 0.24745093, 0.3101854 , 0.01373968],
       [0.34915705, 0.17659939, 0.17796529, 0.33240294, 0.08043011],
       [0.40153956, 0.5917825 , 0.4092766 , 0.34508197, 0.76330129],
       [0.6780825 , 0.9570335 , 0.21657168, 0.93050271, 0.49309851],
       [0.41439288, 0.38603367, 0.4907642 , 0.15363871, 0.65919812],
       [0.82252239, 0.38155066, 0.74127902, 0.86239945, 0.72441495],
       [0.03922591, 0.05553266, 0.18981459, 0.27470493, 0.78491126]])

[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [23]:
5*numpy.identity(5) 

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 