In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
data_dic={
    'col_1':[1,2,3,4,5],
    'col_2':[111,222,333,444,555],
    'col_3':['alpha','bravo','charle',np.nan,np.nan]
}

In [4]:
df=pd.DataFrame(data_dic)

In [5]:
df

col_1  col_2   col_3
0      1    111   alpha
1      2    222   bravo
2      3    333  charle
3      4    444     NaN
4      5    555     NaN

In [9]:
df['col_2'].unique()

array([111, 222, 333, 444, 555], dtype=int64)

In [10]:
print(df['col_1'].unique())
print(df['col_2'].unique())
print(df['col_3'].unique())

[1 2 3 4 5]
[111 222 333 444 555]
['alpha' 'bravo' 'charle' nan]


In [11]:
print(df['col_1'].nunique())
print(df['col_2'].nunique())
print(df['col_3'].nunique())

5
5
3


In [12]:
df

col_1  col_2   col_3
0      1    111   alpha
1      2    222   bravo
2      3    333  charle
3      4    444     NaN
4      5    555     NaN

In [13]:
df['col_1'].value_counts()

col_1
1    1
2    1
3    1
4    1
5    1
Name: count, dtype: int64

In [14]:
df['col_2'].value_counts()

col_2
111    1
222    1
333    1
444    1
555    1
Name: count, dtype: int64

In [15]:
df['col_3'].value_counts()

col_3
alpha     1
bravo     1
charle    1
Name: count, dtype: int64

In [16]:
df['col_3'].isnull()

0    False
1    False
2    False
3     True
4     True
Name: col_3, dtype: bool

In [17]:
df['col_3'].isnull().sum()

2

In [18]:
df['col_3'].count()

3

In [19]:
df

col_1  col_2   col_3
0      1    111   alpha
1      2    222   bravo
2      3    333  charle
3      4    444     NaN
4      5    555     NaN

In [20]:
df.sort_values(by='col_2')

col_1  col_2   col_3
0      1    111   alpha
1      2    222   bravo
2      3    333  charle
3      4    444     NaN
4      5    555     NaN

In [22]:
df.sort_values(by='col_2',ascending=False)

col_1  col_2   col_3
4      5    555     NaN
3      4    444     NaN
2      3    333  charle
1      2    222   bravo
0      1    111   alpha

In [23]:
df.shape

(5, 3)

In [24]:
def square(value):
    return value*value

In [25]:
square(5)

25

In [26]:
square(9)

81

In [27]:
df

col_1  col_2   col_3
0      1    111   alpha
1      2    222   bravo
2      3    333  charle
3      4    444     NaN
4      5    555     NaN

In [28]:
df['col_2'].apply(square)

0     12321
1     49284
2    110889
3    197136
4    308025
Name: col_2, dtype: int64

In [29]:
df['col_1'].apply(square)

0     1
1     4
2     9
3    16
4    25
Name: col_1, dtype: int64

In [30]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [31]:
df.columns

Index(['col_1', 'col_2', 'col_3'], dtype='object')

In [39]:
new_df=df.copy()

In [40]:
new_df

col_1  col_2   col_3
0      1    111   alpha
1      2    222   bravo
2      3    333  charle
3      4    444     NaN
4      5    555     NaN

In [41]:
del new_df['col_1']

In [42]:
new_df

col_2   col_3
0    111   alpha
1    222   bravo
2    333  charle
3    444     NaN
4    555     NaN

In [43]:
new_df.insert(1,'new_col2',[1,22,333,4444,55555])

In [44]:
new_df

col_2  new_col2   col_3
0    111         1   alpha
1    222        22   bravo
2    333       333  charle
3    444      4444     NaN
4    555     55555     NaN

In [45]:
new_df['dddd']=1111

In [46]:
new_df

col_2  new_col2   col_3  dddd
0    111         1   alpha  1111
1    222        22   bravo  1111
2    333       333  charle  1111
3    444      4444     NaN  1111
4    555     55555     NaN  1111